### ISSUE TITLE
Heroku auth &&|| db issues

### ISSUE THREAD

**Issue by ChiefDakota** [ChiefDakota/react-on-rails-spa#16]
Works locally, but on production can't login or sign up - getting 500s
Was getting 404s with `undefined`s, and started getting the 500s after removing [this](https://github.com/ChiefDakota/react-on-rails-spa/commit/02e16b43b71595148c1ebdb4853e60407cccbe0a#diff-9d6c51dc1a9756a11b29e7c4efea6413L5) from `client/packs/services/AuthService.js`

![image](https://user-images.githubusercontent.com/17812895/56415498-bf65e380-6242-11e9-9745-08c6a34eea2c.png)

```
2019-04-19T08:13:41.590371+00:00 app[web.1]: D, [2019-04-19T08:13:41.590202 #14] DEBUG -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]   User Load (2.9ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."email" = $1 LIMIT $2  [["email", "chief@dogs.com"], ["LIMIT", 1]]
2019-04-19T08:13:41.701111+00:00 app[web.1]: D, [2019-04-19T08:13:41.700954 #14] DEBUG -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]    (0.7ms)  BEGIN
2019-04-19T08:13:41.706408+00:00 app[web.1]: D, [2019-04-19T08:13:41.706303 #14] DEBUG -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]   User Exists (1.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."id" != $2 LIMIT $3  [["email", "chief@dogs.com"], ["id", 1], ["LIMIT", 1]]
2019-04-19T08:13:41.710507+00:00 app[web.1]: D, [2019-04-19T08:13:41.710412 #14] DEBUG -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]   User Update (0.9ms)  UPDATE "users" SET "last_login" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["last_login", "2019-04-19 08:13:41.699853"], ["updated_at", "2019-04-19 08:13:41.707444"], ["id", 1]]
2019-04-19T08:13:41.712362+00:00 app[web.1]: D, [2019-04-19T08:13:41.712278 #14] DEBUG -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]    (1.3ms)  COMMIT
2019-04-19T08:13:41.713958+00:00 app[web.1]: I, [2019-04-19T08:13:41.713641 #14]  INFO -- : [6e2e17f1-d224-46cc-a110-f86e961e9890] Completed 500 Internal Server Error in 206ms (ActiveRecord: 41.0ms)
2019-04-19T08:13:41.715011+00:00 app[web.1]: F, [2019-04-19T08:13:41.714930 #14] FATAL -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]
2019-04-19T08:13:41.715085+00:00 app[web.1]: F, [2019-04-19T08:13:41.715018 #14] FATAL -- : [6e2e17f1-d224-46cc-a110-f86e961e9890] TypeError (no implicit conversion of nil into String):
2019-04-19T08:13:41.715156+00:00 app[web.1]: F, [2019-04-19T08:13:41.715091 #14] FATAL -- : [6e2e17f1-d224-46cc-a110-f86e961e9890]
2019-04-19T08:13:41.715241+00:00 app[web.1]: F, [2019-04-19T08:13:41.715175 #14] FATAL -- : [6e2e17f1-d224-46cc-a110-f86e961e9890] app/controllers/user_token_controller.rb:22:in `new'
2019-04-19T08:13:41.715242+00:00 app[web.1]: [6e2e17f1-d224-46cc-a110-f86e961e9890] app/controllers/user_token_controller.rb:22:in `auth_token'
2019-04-19T08:13:41.715244+00:00 app[web.1]: [6e2e17f1-d224-46cc-a110-f86e961e9890] app/controllers/user_token_controller.rb:5:in `create'
2019-04-19T08:13:41.717052+00:00 heroku[router]: at=info method=POST path="/user_token" host=react-on-rails-spa.herokuapp.com request_id=6e2e17f1-d224-46cc-a110-f86e961e9890 fwd="172.89.19.185" dyno=web.1 connect=0ms service=214ms status=500 bytes=243 protocol=https
```

**Comment by ChiefDakota** [comment]
Fixed in #17 🎉
